name: CI/CD with GitHub Pages

on:
  push:
    branches:
      - main # Modify this to the branch you want to trigger the workflow on

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check HTML
        id: html-validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Check HTML Validation Status
        id: check-validation
        run: echo "::set-output name=status::${{ job.status }}"

      - name: Deploy to GitHub Pages
        if: steps.check-validation.outputs.status == 'success'
        uses: actions/deploy-pages@v2
